Re-logging/front-web

- src/app/events/[id]/page.tsx
- src/app/news/[id]/page.tsx
- src/app/page.tsx
- src/components/EventListGrid.tsx
- src/components/EventsContent.tsx
- src/components/NewsContent.tsx
- src/components/NewsListGrid.tsx
#2 
close #2 
>  FEAT : 뉴스 및 이벤트 라우팅 및 디테일 페이지 추가
> FEAT : 뉴스 및 이벤트 라우팅 및 디테일 페이지 추가

- package-lock.json
- package.json
- public/mockServiceWorker.js
- src/app/layout.tsx
- src/app/msw-provider.tsx
- src/mocks/browser.ts
- src/mocks/handlers.ts
- src/mocks/server.ts
#6 
MSW 기본 설치 완료
> https://velog.io/@soleil_lucy_75/Nextjs-v14%EC%97%90-MSW-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EC%A0%81%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0 해당 블로그 참고하여 MSW 구축하였습니다.
> FEAT: MSW 구축

- src/components/layouts/CommonLayout.tsx
> FIX: CommonLayout 이름 변경

- src/app/layout.tsx
> FIX: 레이아웃 컴포넌트 import 에러 수정

- src/app/events/[id]/page.tsx
- src/app/news/[id]/page.tsx
- src/app/page.tsx
- src/components/HomeButton.tsx
- src/components/LabeledContent.tsx
- tailwind.config.ts
> STYLES: 모바일 디자인 수정

- src/app/news/[id]/page.tsx
- src/app/page.tsx
- src/components/NewsCard.tsx
- src/hooks/useEventsQueries.ts
- src/hooks/useNewsQueries.ts
뉴스 디테일 오른쪽 사이드바 에러 이슈
잘못된 api를 호출하는 상황이 있어서 if조건을 달아 변경했습니다.
>
> FIX: 뉴스 디테일 페이지 오른쪽 사이드바 에러 수정

- src/components/NewsCard.tsx
> HOTFIX: 이미지 null 에러대응

- next.config.mjs
- src/components/NewsCard.tsx
#25  
뉴스 카드 컴포넌트 관련해서 스타일을 수정하였습니다.
> STYLE: 뉴스 카드 디자인 수정

- .github/workflows/autoDeploy.yml
> FIX: yml 수정

- src/app/events/[id]/page.tsx
- src/app/news/[id]/page.tsx
- src/components/ContentList.tsx
- src/components/EventListGrid.tsx
- src/components/NewsListGrid.tsx
- src/components/ui/sheet.tsx
- src/hooks/useContentList.ts
- src/mocks/handlers.ts
- src/types/IEvent.ts
> [FIX] vercel 배포 에러 수정

- src/hooks/useEventsQueries.ts
- src/mocks/handlers.ts
> FIX: Plogging Event 관련 api 엔드포인트 수정

- src/components/layouts/CommonLayout.tsx
- src/components/ui/dialog.tsx
> FIX: build 에러 수정

- src/app/events/[id]/page.tsx
- src/app/news/[id]/page.tsx
- src/components/NewsCard.tsx
- src/components/ui/EventCard.tsx
Close #44 
메인 페이지 및 디테일 페이지에서 레이아웃 모바일 및 데스크탑 레이아웃 깨짐 현상 수정
>
> STYLE: 메인 페이지 및 디테일 페이지 레이아웃 사이즈 수정

- src/components/LoginModal.tsx
- src/components/MobileNav.tsx
- src/components/OauthButton.tsx
- src/components/layouts/CommonLayout.tsx
- src/components/ui/dialog.tsx
> STYLE: 로그인 컴포넌트 스타일 수정

- src/app/news/[id]/page.tsx
Close #54
> #54 
> 페이지네이션 인자 값 변경
>
> FIX: 뉴스 디테일 페이지네이션 수정

- src/app/layout.tsx
- src/app/oauth/success/page.tsx
- src/components/SessionWrapper.tsx
> FEAT: 로그인 기능 추가

- src/app/layout.tsx
- src/components/layouts/CommonLayout.tsx
> #58 
> SessionProvider가 로그인 버튼 보다 상위에 위치하도록 변경
>
> FIX: SessionWrapper 위치 변경

- src/app/api/auth/[...nextauth]/route.ts
- src/app/oauth/success/page.tsx
- src/auth.config.ts
- src/auth.ts
- src/components/LoginButton.tsx
- src/types/next-auth.d.ts
> FIX: 로그인 액세스 토큰 확인

- src/app/oauth/success/page.tsx
- src/components/GoogleOauthButton.tsx
- src/components/KakaoOauthButton.tsx
- src/components/LoginModal.tsx
- src/components/OauthButton.tsx
> #61 
> oauth 로그인 이후 인가 코드 추출
>
> FEAT: 로그인 리다이렉션 인가 코드 추출

- src/app/oauth/success/page.tsx
- src/components/GoogleOauthButton.tsx
- src/components/KakaoOauthButton.tsx
> #26 
> 로그인 소셜 타입을 로그인 타입에 따라 동적으로 바꾸었습니다.
>
> FEAT: 로그인 소셜 타입 동적 분리

- src/components/layouts/Footer.tsx
> FEAT: footer 링크 연결

- src/hooks/useEventsQueries.ts
- src/hooks/useMeetupList.ts
> FIX: 쿼리 url 수정

- src/app/oauth/success/page.tsx
> FIX: 로그인 리다이렉트 URL 수정

- src/app/oauth/success/[id]/page.tsx
- src/components/AuthProvider.tsx
- src/components/MyPageButton.tsx
- src/hooks/useAuthFetch.ts
- src/hooks/useOAuth.ts
- src/middleware.ts
- src/store/authStore.ts
> #26 
> 미들웨어 추가 및 액세스 토큰 전역관리 추가
>
> FEAT : 로그인 미들웨어 추가 및 전역관리 추가

- src/app/@modal/(.)account/page.tsx
- src/app/@modal/(.)profile/page.tsx
- src/components/modal/MyPageModal.tsx
- src/store/authStore.ts
Close #56
> #56
> 마이페이지 관련 기능 User전역 상태 활용
>
> FEAT: 마이 페이지 전역 상태 활용

- src/app/@modal/(.)account/page.tsx
- src/app/@modal/(.)profile/page.tsx
- src/hooks/useUpdateAccount.ts
- src/hooks/useUpdateProfile.ts
- src/store/authStore.ts
> #56
> 마이페이지 서브 페이지들 api 연결
>
> FEAT: 마이페이지 계정 관련 설정 api 추가

- src/app/meetup/[id]/page.tsx
- src/app/news/[id]/page.tsx
- src/app/page.tsx
- src/components/LoadingSpinner.tsx
- src/components/MeetupCard.tsx
- src/components/NewsCard.tsx
- src/hooks/useMeetupList.ts
- src/hooks/useNewsQueries.ts
- src/types/IMeetup.ts
> #85 
> 로딩 스피너 컴포넌트 추가 및 컴포넌트 스타일 수정
>
> STYLE: 전반적인 스타일링 수정 및 컴포넌트 수정

- src/app/api/user/account/route.ts
> #83 
> credentials 옵션 이슈로 로직 수정
>
> FIX: 리프레쉬 토큰 옵션 수정

- src/app/@modal/(.)profile/page.tsx
- src/app/api/user/profile/route.ts
- src/hooks/useUpdateProfile.ts
- src/lib/fetch.ts
> FEAT: 로그인 fetch 생성

- next.config.mjs
- package-lock.json
- package.json
- src/app/events/[id]/page.tsx
- src/components/EventCard.tsx
- src/components/layouts/CommonLayout.tsx
- src/components/ui/button.tsx
- src/components/ui/carousel.tsx
- src/types/IEvent.ts
> ex) #93
> 이벤트 디테일 및 리스트 이미지 컴포넌트 수정
>
> FEAT: 우리 동네 플로깅 이미지 리스트 구현

- src/app/@modal/(.)meetup/new/page.tsx
- src/app/@modal/(.)profile/page.tsx
- src/app/api/ploggingMeetups/route.ts
- src/app/meetup/[id]/page.tsx
- src/hooks/useMeetupList.ts
> #64 
> 모임 생성 api 연결 및 모임 디테일 페이지 시간 dayjs활용 포맷 수정
>
> [FEATURE] 유저 플로깅 모임 생성 추가 수정

- src/app/meetup/[id]/page.tsx
- src/app/news/[id]/page.tsx
- src/app/not-found.tsx
- src/components/EventCard.tsx
- src/components/MeetupCard.tsx
- src/components/MeetupList.tsx
- src/components/NewsCard.tsx
- src/components/ui/DircetionButton.tsx
- src/hooks/useMeetupList.ts
> STYLE: 컴포넌트 스타일 수정

- package.json
- src/hooks/useStatusModal.ts
> FIX: 로그인 버튼 수정 에러 해결

- .github/workflows/autoDeploy.yml
> yml 파일 수정
> main과 관련된 ci가 반영되어 급히 수정하였습니다.
> CHORE: develop 브랜치 ci/cd 수정

- src/store/authStore.ts
[업데이트된 User 타입에 userId를 옵셔널로 변경하였습니다.](https://github.com/Re-logging/front-web/pull/132)
> hotfix: build error

- src/app/layout.tsx
- src/components/CommentSection.tsx
- src/components/modal/ReportModal.tsx
> feat: 신고하기 모달 마크업

- src/app/api/comments/route.ts
- src/app/api/report/route.ts
- src/components/comment/CommentInput.tsx
- src/components/comment/CommentList.tsx
- src/components/comment/CommentSection.tsx
- src/components/modal/ReportModal.tsx
신고하기 기능 연동 완료
기존 댓글 api authtoken 이 적용되지 않던 문제 해결
> fix: api auth 적용 및 댓글 신고 api 연결

- src/app/events/[id]/page.tsx
- src/components/comment/CommentList.tsx
드롭다운의 스타일을 조금 개선해 세로로 글자가 배치되던걸 가로로 배치되게 만듬.
삭제된 댓글의 경우 드롭다운메뉴 삭제
> feat: 삭제된 댓글 메뉴 접근막기 및 드롭다운 스타일 개선

- src/app/events/[id]/page.tsx
- src/app/meetup/[id]/page.tsx
- src/app/news/[id]/page.tsx
- src/components/ContentList.tsx
- src/components/LabeledContent.tsx
- src/components/status/LoadingSkeleton.tsx
- src/utils/linkifyContent.tsx
- 로딩 스켈레톤 컴포넌트 컬럼, 로우 갯수 커스텀 할 수 있도록 수정
- 컨텐츠 하이퍼링크 스타일 추가
- 디테일 페이지 디바이더 높이 수정
> [STYLE] 스타일 수정 사항 반영

- src/app/events/[id]/_EventDetailSection.tsx
- src/app/events/[id]/_EventSidebar.tsx
- src/app/events/[id]/page.tsx
- src/app/layout.tsx
- src/app/meetup/[id]/_MeetupDetailSection.tsx
- src/app/meetup/[id]/_MeetupSidebar.tsx
- src/app/meetup/[id]/page.tsx
- src/app/news/[id]/_NewsDetailSection.tsx
- src/app/news/[id]/_NewsSidebar.tsx
- src/app/news/[id]/page.tsx
- src/app/robots.ts
- src/hooks/useEventsQueries.ts
- src/hooks/useMeetupList.ts
- 메인 SEO 추가
- 디테일 페이지 SEO  추가
- 디테일 페이지 리팩토링
> [FEATURE] SEO 추가 

- src/app/api/report/route.ts
- src/components/comment/CommentList.tsx
신고하기 500에러 오류를 해결하였습니다.
commentId가 null로 되어있어서 발생하는 오류였습니다
> fix: report 500 error

- src/app/@modal/(.)meetup/new/page.tsx
- src/hooks/useMeetupList.ts
> [FIX] 필수입력 조건 변경

- src/app/@modal/(.)meetup/new/page.tsx
- src/hooks/useMeetupList.ts
> [FIX ]필수입력 조건 변경

- src/app/@modal/(.)meetup/new/page.tsx
- src/components/ui/calendar.tsx
Close #107
#107 
>  플로깅 모임 생성 캘린더 관련 css 이슈 해결
>
> BUG: 새 모임 등록하기 모임 시간 설정
